import { useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ErrorBoundary } from '@/components/error-boundary';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';
import {
  ArrowRight, BookOpen, CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, ExternalLink,
  Flame, FolderOpen, Heart, Home as HomeIcon, Layers3, Library, Menu, MessageCircle,
  MoreHorizontal, NotebookPen, Palette, Play, Plus, RotateCcw, Search, Send, Settings,
  Sparkles, Star, Target, Timer, Trash2, Trophy, UserRound, X, Zap,
} from 'lucide-react';
import { Link, Route, Router as WouterRouter, Switch, useLocation } from 'wouter';

type Batch = {
  _id?: string; id?: string; name?: string; byName?: string; description?: string;
  startDate?: string; endDate?: string; language?: string; previewImage?: string;
  feeTotal?: number; type?: string; slug?: string; category?: string; exam?: string;
  class?: string; provider?: string; [key: string]: unknown;
};
type Note = { id: string; title: string; body: string; createdAt: string };
type Countdown = { id: string; title: string; date: string; color: string };
type Theme = 'light' | 'dark' | 'sandalwood' | 'forest' | 'ocean' | 'sakura' | 'dracula' | 'lavender' | 'cyberpunk' | 'system';

const queryClient = new QueryClient();
const FALLBACK = '/assets/codex-telegram.png';
const themes: { id: Theme; label: string; swatch: string }[] = [
  { id: 'light', label: 'Light Mode', swatch: '#f97355' }, { id: 'dark', label: 'Dark Mode', swatch: '#f3a58d' },
  { id: 'sandalwood', label: 'Sandalwood', swatch: '#ad5c35' }, { id: 'forest', label: 'Forest Emerald', swatch: '#217d67' },
  { id: 'ocean', label: 'Ocean Deep', swatch: '#197b9b' }, { id: 'sakura', label: 'Sakura Blossom', swatch: '#dc557a' },
  { id: 'dracula', label: 'Dracula Midnight', swatch: '#bd93f9' }, { id: 'lavender', label: 'Lavender Mist', swatch: '#7651bf' },
  { id: 'cyberpunk', label: 'Cyberpunk Neon', swatch: '#ec43bb' }, { id: 'system', label: 'System Default', swatch: '#4f617a' },
];

function usePersistent<T>(key: string, initial: T) {
  const [value, setValue] = useState<T>(() => {
    try { const saved = localStorage.getItem(key); return saved ? JSON.parse(saved) as T : initial; } catch { return initial; }
  });
  useEffect(() => { localStorage.setItem(key, JSON.stringify(value)); }, [key, value]);
  return [value, setValue] as const;
}

function App() {
  return <QueryClientProvider client={queryClient}><TooltipProvider><WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/, '')}><Routed /></WouterRouter><Toaster /></TooltipProvider></QueryClientProvider>;
}

function Routed() {
  const [location] = useLocation();
  return <ErrorBoundary resetKey={location}><Shell><Switch><Route path="/" component={Home} /><Route path="/profile" component={Profile} /><Route component={NotFound} /></Switch></Shell></ErrorBoundary>;
}

function Shell({ children }: { children: ReactNode }) {
  const [location] = useLocation();
  const [theme, setTheme] = usePersistent<Theme>('codex-theme', 'light');
  const [community, setCommunity] = useState(false);
  useEffect(() => {
    const root = document.documentElement;
    const media = window.matchMedia('(prefers-color-scheme: dark)');
    const apply = () => {
      const resolved = theme === 'system' ? (media.matches ? 'dark' : 'light') : theme;
      root.setAttribute('data-theme', resolved);
      root.classList.toggle('dark', resolved === 'dark' || resolved === 'dracula' || resolved === 'cyberpunk');
      root.style.colorScheme = resolved === 'dark' || resolved === 'dracula' || resolved === 'cyberpunk' ? 'dark' : 'light';
    };
    apply();
    media.addEventListener('change', apply);
    return () => media.removeEventListener('change', apply);
  }, [theme]);
  useEffect(() => {
    if (!localStorage.getItem('codex-community-seen')) setCommunity(true);
    const open = () => setCommunity(true);
    window.addEventListener('codex-open-community', open);
    return () => window.removeEventListener('codex-open-community', open);
  }, []);
  const closeCommunity = () => { localStorage.setItem('codex-community-seen', '1'); setCommunity(false); };
  const nav = [{ href: '/', label: 'Home', icon: HomeIcon }, { href: '/profile', label: 'Profile', icon: UserRound }];
  return <div className="app-shell noise">
    <aside className="fixed inset-y-0 left-0 z-30 hidden w-[248px] flex-col border-r border-border bg-sidebar px-5 py-6 text-sidebar-foreground md:flex">
      <Link href="/" className="mb-12 flex items-center gap-3 px-2" data-testid="link-brand">
        <img src={FALLBACK} alt="CodeXStudys mark" className="h-10 w-10 rounded-xl object-cover ring-2 ring-primary/30" />
        <span className="display-font text-xl font-bold tracking-tight">Code<span className="text-primary">X</span><br /><span className="text-sm font-medium tracking-[.2em] text-sidebar-foreground/70">STUDYS</span></span>
      </Link>
      <p className="mb-3 px-3 text-[10px] font-bold uppercase tracking-[.22em] text-sidebar-foreground/45">Your study space</p>
      <nav className="space-y-1.5">{nav.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold transition ${location === href ? 'bg-primary text-primary-foreground shadow-lg shadow-primary/20' : 'text-sidebar-foreground/70 hover:bg-sidebar-foreground/10 hover:text-sidebar-foreground'}`} data-testid={`link-${label.toLowerCase()}`}><Icon size={18} />{label}</Link>)}</nav>
      <div className="mt-auto rounded-2xl border border-sidebar-foreground/10 bg-sidebar-foreground/5 p-4">
        <div className="mb-3 flex h-9 w-9 items-center justify-center rounded-xl bg-accent text-accent-foreground"><Zap size={18} /></div>
        <p className="display-font text-sm font-bold">Small steps. Big ranks.</p>
        <p className="mt-1 text-xs leading-5 text-sidebar-foreground/55">Make today count, one focused session at a time.</p>
      </div>
    </aside>
    <main className="desktop-main min-h-[100dvh] pb-24 md:pb-8">{children}</main>
    {community && <CommunityModal onClose={closeCommunity} />}
    <nav className="fixed bottom-0 left-0 right-0 z-40 flex h-[74px] items-center justify-around border-t border-border bg-card/95 px-6 shadow-[0_-8px_30px_hsl(var(--foreground)/.06)] backdrop-blur md:hidden">
      {nav.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className={`flex min-w-[78px] flex-col items-center gap-1 rounded-xl py-2 text-[11px] font-bold transition ${location === href ? 'text-primary' : 'text-muted-foreground'}`} data-testid={`mobile-link-${label.toLowerCase()}`}><span className={`flex h-8 w-12 items-center justify-center rounded-full ${location === href ? 'bg-primary/12' : ''}`}><Icon size={20} /></span>{label}</Link>)}
    </nav>
  </div>;
}

function Home() {
  const [batches, setBatches] = useState<Batch[]>([]);
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading');
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('All Batches');
  const [favorites, setFavorites] = usePersistent<string[]>('codex-favorites', []);
  const [searchOpen, setSearchOpen] = useState(false);
  useEffect(() => {
    fetch('/batches.json').then(r => { if (!r.ok) throw new Error('Could not load batches'); return r.json(); })
      .then(data => { const raw = Array.isArray(data) ? data : data.batches; const seen = new Set<string>(); const clean = (raw || []).filter((b: Batch) => { const id = String(b._id || b.id || b.slug || b.name); if (seen.has(id)) return false; seen.add(id); return true; }); setBatches(clean); setStatus('ready'); })
      .catch(() => setStatus('error'));
  }, []);
  const exams = useMemo(() => {
    const names = batches.map(b => detectExam(b)).filter(Boolean) as string[];
    return ['All Batches', 'Favorites', ...Array.from(new Set(names))];
  }, [batches]);
  const shown = useMemo(() => batches.filter(b => {
    const haystack = Object.entries(b).map(([k, v]) => `${k} ${String(v ?? '')}`).join(' ').toLowerCase();
    const matchesQuery = haystack.includes(query.toLowerCase().trim());
    const id = getId(b);
    const matchesFilter = filter === 'All Batches' || (filter === 'Favorites' ? favorites.includes(id) : detectExam(b) === filter);
    return matchesQuery && matchesFilter;
  }), [batches, query, filter, favorites]);
  const toggleFavorite = (id: string) => setFavorites(favorites.includes(id) ? favorites.filter(x => x !== id) : [...favorites, id]);
  return <section className="page-in mx-auto max-w-[1400px] px-4 py-5 sm:px-8 md:px-10 md:py-8">
    <header className="mb-8 flex items-center justify-between">
      <div className="flex items-center gap-3 md:hidden"><img src={FALLBACK} alt="" className="h-9 w-9 rounded-xl object-cover" /><span className="display-font font-bold">Code<span className="text-primary">X</span>Studys</span></div>
      <div className="hidden md:block"><p className="mb-1 text-xs font-bold uppercase tracking-[.22em] text-primary">{new Date().toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}</p><h1 className="display-font text-3xl font-bold tracking-tight">Choose your next <span className="text-primary">breakthrough.</span></h1></div>
      <div className="flex items-center gap-2 md:ml-auto">
        <button onClick={() => setSearchOpen(!searchOpen)} className="flex h-10 w-10 items-center justify-center rounded-full border border-border bg-card text-muted-foreground transition hover:border-primary hover:text-primary md:hidden" aria-label="Toggle search" data-testid="button-toggle-search"><Search size={18} /></button>
        <Link href="/profile" className="flex h-10 w-10 items-center justify-center rounded-full border border-border bg-card text-muted-foreground transition hover:border-primary hover:text-primary" aria-label="Open profile" data-testid="link-header-profile"><UserRound size={18} /></Link>
      </div>
    </header>
    <div className="mb-7 rounded-[1.5rem] bg-sidebar p-5 text-sidebar-foreground shadow-xl shadow-sidebar/10 sm:p-7 md:flex md:items-end md:justify-between">
      <div className="max-w-xl"><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-accent"><Sparkles size={15} /> Built for the Indian student</div><h2 className="display-font text-2xl font-bold leading-tight sm:text-3xl">Your library, <span className="text-primary">without the noise.</span></h2><p className="mt-2 max-w-md text-sm leading-6 text-sidebar-foreground/65">Find the right batch, save what matters, and keep moving towards the score you want.</p></div>
      <div className="mt-5 flex gap-5 border-t border-sidebar-foreground/10 pt-4 md:mt-0 md:border-0 md:pt-0"><div><p className="display-font text-2xl font-bold text-accent">{batches.length || '—'}</p><p className="text-[11px] text-sidebar-foreground/55">batches to explore</p></div><div><p className="display-font text-2xl font-bold">{favorites.length}</p><p className="text-[11px] text-sidebar-foreground/55">saved for later</p></div></div>
    </div>
    <div className={`mb-5 ${searchOpen ? 'block' : 'hidden md:block'}`}><label className="relative block"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-muted-foreground" size={18} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search batches, exams, classes, languages..." className="h-12 w-full rounded-2xl border border-border bg-card pl-11 pr-11 text-sm outline-none transition placeholder:text-muted-foreground/65 focus:border-primary focus:ring-4 focus:ring-primary/10" data-testid="input-search-batches" /><button onClick={() => setQuery('')} className={`absolute right-3 top-1/2 -translate-y-1/2 rounded-full p-1.5 text-muted-foreground hover:bg-muted ${query ? '' : 'hidden'}`} aria-label="Clear search" data-testid="button-clear-search"><X size={15} /></button></label></div>
    <div className="mb-6 flex gap-2 overflow-x-auto pb-1 scrollbar-none">{exams.map((item, i) => <button key={item} onClick={() => setFilter(item)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold transition ${filter === item ? 'bg-primary text-primary-foreground shadow-md shadow-primary/20' : 'border border-border bg-card text-muted-foreground hover:border-primary/50 hover:text-foreground'}`} data-testid={`filter-${item.toLowerCase().replace(/\s/g, '-')}`}>{item === 'Favorites' && <Heart size={13} className="mr-1 inline" fill="currentColor" />}{item}</button>)}</div>
    {status === 'loading' && <BatchSkeleton />}
    {status === 'error' && <StateCard icon={<RotateCcw />} title="The library took a study break." body="We couldn't load the batches right now. Check your connection and try again." action="Try again" onAction={() => window.location.reload()} />}
    {status === 'ready' && !shown.length && <StateCard icon={filter === 'Favorites' ? <Heart /> : <Search />} title={filter === 'Favorites' ? 'No saved batches yet.' : 'No batches match that search.'} body={filter === 'Favorites' ? 'Tap the heart on any batch to keep it close.' : 'Try a wider search or switch back to all batches.'} action={filter === 'Favorites' ? 'Browse all batches' : 'Clear search'} onAction={() => { setFilter('All Batches'); setQuery(''); }} />}
    {status === 'ready' && shown.length > 0 && <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{shown.map((batch, i) => <BatchCard key={getId(batch)} batch={batch} index={i} favorite={favorites.includes(getId(batch))} onFavorite={() => toggleFavorite(getId(batch))} />)}</div>}
  </section>;
}

function BatchCard({ batch, favorite, onFavorite, index }: { batch: Batch; favorite: boolean; onFavorite: () => void; index: number }) {
  const id = getId(batch); const name = batch.name || 'Untitled batch'; const exam = detectExam(batch);
  const openUrl = `https://stream.testuk.org/subjects?batchId=${encodeURIComponent(id)}&batchName=${encodeURIComponent(name)}`;
  return <article className="card-lift group overflow-hidden rounded-2xl border border-card-border bg-card" style={{ animationDelay: `${Math.min(index, 8) * 35}ms` }} data-testid={`card-batch-${id}`}>
    <div className="relative aspect-[1.75/1] overflow-hidden bg-muted"><img src={batch.previewImage || FALLBACK} alt={`${name} banner`} loading="lazy" onError={e => { e.currentTarget.src = FALLBACK; }} className="h-full w-full object-contain transition duration-500 group-hover:scale-[1.03]" /><div className="absolute inset-0 bg-gradient-to-t from-foreground/55 via-transparent to-transparent opacity-80" /><button onClick={onFavorite} className={`absolute right-3 top-3 flex h-9 w-9 items-center justify-center rounded-full border backdrop-blur transition ${favorite ? 'border-primary/30 bg-primary text-primary-foreground' : 'border-white/35 bg-foreground/20 text-white hover:bg-white hover:text-primary'}`} aria-label={favorite ? `Remove ${name} from favorites` : `Save ${name} to favorites`} data-testid={`button-favorite-${id}`}><Heart size={17} fill={favorite ? 'currentColor' : 'none'} /></button><span className="absolute bottom-3 left-3 rounded-md bg-card/90 px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-foreground">{batch.type === 'REGULAR' ? 'Course' : 'Batch'}</span></div>
    <div className="p-4"><h3 className="display-font line-clamp-2 min-h-[42px] text-[16px] font-bold leading-5">{name}</h3><p className="mt-1 line-clamp-1 text-xs text-muted-foreground">{batch.byName || batch.description || 'Structured learning for your next goal'}</p><div className="mt-4 flex flex-wrap gap-1.5">{exam && <span className="rounded-md bg-primary/10 px-2 py-1 text-[10px] font-bold text-primary">{exam}</span>}<span className="rounded-md bg-secondary px-2 py-1 text-[10px] font-bold text-secondary-foreground">{batch.language || 'English'}</span>{batch.class && <span className="rounded-md bg-muted px-2 py-1 text-[10px] font-bold text-muted-foreground">{String(batch.class)}</span>}</div><div className="mt-4 flex items-center justify-between border-t border-border pt-3"><span className="flex items-center gap-1 text-[11px] text-muted-foreground"><CalendarDays size={13} />{batch.startDate || 'Self-paced'}</span><a href={openUrl} target="_blank" rel="noreferrer" className="flex items-center gap-1.5 rounded-lg bg-primary px-3 py-2 text-xs font-bold text-primary-foreground transition hover:brightness-95 active:scale-95" data-testid={`link-study-${id}`}>Study now <ArrowRight size={14} /></a></div></div>
  </article>;
}

function Profile() {
  const [mood, setMood] = usePersistent('codex-mood', 'Focused');
  const [notes, setNotes] = usePersistent<Note[]>('codex-notes', []);
  const [countdowns, setCountdowns] = usePersistent<Countdown[]>('codex-countdowns', []);
  const [favorites] = usePersistent<string[]>('codex-favorites', []);
  const [effects, setEffects] = usePersistent('codex-effects', 'None');
  const [timerStats, setTimerStats] = usePersistent('codex-timer-stats', { sessions: 0, minutes: 0 });
  const [activity, setActivity] = usePersistent<string[]>('codex-activity', []);
  const [theme, setTheme] = usePersistent<Theme>('codex-theme', 'light');
  const [totalBatches, setTotalBatches] = useState(0);
  const [settings, setSettings] = useState(false);
  const [noteModal, setNoteModal] = useState(false);
  const [countdownModal, setCountdownModal] = useState(false);
  const [editingNote, setEditingNote] = useState<Note | null>(null);
  const [editingCountdown, setEditingCountdown] = useState<Countdown | null>(null);
  useEffect(() => { fetch('/batches.json').then(r => r.json()).then(data => setTotalBatches(Array.isArray(data) ? data.length : (data.batches || []).length)).catch(() => setTotalBatches(0)); }, []);
  useEffect(() => {
    const root = document.documentElement;
    const media = window.matchMedia('(prefers-color-scheme: dark)');
    const apply = () => root.setAttribute('data-theme', theme === 'system' ? (media.matches ? 'dark' : 'light') : theme);
    apply();
    media.addEventListener('change', apply);
    return () => media.removeEventListener('change', apply);
  }, [theme]);
  const addNote = (note: Note) => { setNotes(editingNote ? notes.map(n => n.id === note.id ? note : n) : [note, ...notes]); setNoteModal(false); setEditingNote(null); };
  const saveCountdown = (item: Countdown) => { setCountdowns((editingCountdown ? countdowns.map(c => c.id === item.id ? item : c) : [...countdowns, item]).sort((a, b) => a.date.localeCompare(b.date))); setCountdownModal(false); setEditingCountdown(null); };
  const logSession = () => { setTimerStats({ sessions: timerStats.sessions + 1, minutes: timerStats.minutes + 25 }); const today = new Date().toISOString().slice(0, 10); if (!activity.includes(today)) setActivity([...activity, today]); };
  const xp = timerStats.sessions * 25;
  const level = Math.floor(xp / 500) + 1;
  const progress = xp % 500;
  return <section className="page-in mx-auto max-w-[1400px] px-4 py-5 sm:px-8 md:px-10 md:py-8">
    <header className="mb-7 flex items-center justify-between"><div><p className="mb-1 text-xs font-bold uppercase tracking-[.2em] text-primary">Your corner</p><h1 className="display-font text-3xl font-bold tracking-tight">Good to see you, <span className="text-primary">scholar.</span></h1><p className="mt-1 text-sm text-muted-foreground">A little progress, every day.</p></div><button onClick={() => setSettings(true)} className="flex h-10 w-10 items-center justify-center rounded-full border border-border bg-card text-muted-foreground transition hover:border-primary hover:text-primary" aria-label="Open profile settings" data-testid="button-profile-settings"><Settings size={18} /></button></header>
    <div className="mb-5 grid gap-4 lg:grid-cols-[1.45fr_1fr]">
       <div className="relative overflow-hidden rounded-[1.5rem] bg-sidebar p-5 text-sidebar-foreground shadow-xl shadow-sidebar/10 sm:p-7"><div className="absolute -right-8 -top-12 h-44 w-44 rounded-full border-[24px] border-primary/20" /><div className="absolute -bottom-20 right-24 h-44 w-44 rounded-full border-[18px] border-accent/15" /><div className="relative"><div className="flex items-start gap-4"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-primary text-xl font-bold text-primary-foreground">C</div><div><h2 className="display-font text-xl font-bold">Your study desk</h2><p className="mt-1 text-xs text-sidebar-foreground/60">Level {level} · Consistency is your superpower</p></div></div><div className="mt-7 flex items-end justify-between"><div><p className="display-font text-4xl font-bold">{xp.toLocaleString()} <span className="text-sm font-semibold text-accent">XP</span></p><div className="mt-2 h-2 w-44 overflow-hidden rounded-full bg-sidebar-foreground/15"><div className="h-full rounded-full bg-accent transition-all" style={{ width: `${progress / 5}%` }} /></div><p className="mt-1 text-[10px] text-sidebar-foreground/55">{500 - progress} XP to Level {level + 1}</p></div><div className="text-right"><Flame className="ml-auto text-accent" size={25} /><p className="display-font text-xl font-bold">{getCurrentStreak(activity)} days</p><p className="text-[10px] text-sidebar-foreground/55">study streak</p></div></div></div></div>
      <div className="rounded-[1.5rem] border border-card-border bg-card p-5 sm:p-6"><div className="mb-4 flex items-center justify-between"><div><p className="display-font text-base font-bold">How are you feeling?</p><p className="mt-1 text-xs text-muted-foreground">Set the tone for today.</p></div><span className="rounded-full bg-secondary px-2.5 py-1 text-[10px] font-bold text-secondary-foreground">Today</span></div><div className="grid grid-cols-4 gap-2">{['Focused', 'Steady', 'Tired', 'Pumped'].map((item, i) => <button key={item} onClick={() => setMood(item)} className={`rounded-xl border p-2.5 text-center transition ${mood === item ? 'border-primary bg-primary/10 text-primary' : 'border-border text-muted-foreground hover:border-primary/40'}`} data-testid={`button-mood-${item.toLowerCase()}`}><span className="mx-auto mb-1 flex h-8 w-8 items-center justify-center rounded-full bg-muted text-xs font-bold">{['F', 'S', 'T', 'P'][i]}</span><span className="text-[10px] font-bold">{item}</span></button>)}</div></div>
    </div>
     <div className="mb-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat icon={<Heart />} value={favorites.length.toString()} label="Saved batches" accent="primary" /><Stat icon={<BookOpen />} value={totalBatches ? totalBatches.toString() : '—'} label="Total batches" accent="secondary" /><Stat icon={<Clock3 />} value={`${timerStats.minutes}m`} label="Study time" accent="accent" /><Stat icon={<Trophy />} value={getCurrentStreak(activity).toString()} label="Study streak" accent="primary" /></div>
    <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
       <div className="space-y-5"><WeeklyActivity activity={activity} /><div className="rounded-2xl border border-card-border bg-card p-5"><SectionTitle icon={<CalendarDays />} title="Keep an eye on the finish line" action={<button onClick={() => { setEditingCountdown(null); setCountdownModal(true); }} className="flex items-center gap-1 rounded-lg bg-primary/10 px-3 py-2 text-xs font-bold text-primary transition hover:bg-primary/20" data-testid="button-add-countdown"><Plus size={15} /> Add exam</button>} />{countdowns.length === 0 ? <EmptyInline icon={<Target />} text="Add an exam to make your countdown feel real." action="Create countdown" onClick={() => { setEditingCountdown(null); setCountdownModal(true); }} /> : <div className="mt-4 grid gap-3 sm:grid-cols-2">{countdowns.map(c => <CountdownItem key={c.id} item={c} onEdit={() => { setEditingCountdown(c); setCountdownModal(true); }} onDelete={() => setCountdowns(countdowns.filter(x => x.id !== c.id))} />)}</div>}</div></div>
       <div className="space-y-5"><Pomodoro stats={timerStats} onSession={logSession} /><Flashcards /><div className="rounded-2xl border border-card-border bg-card p-5"><SectionTitle icon={<NotebookPen />} title="Quick notes" action={<button onClick={() => { setEditingNote(null); setNoteModal(true); }} className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary transition hover:bg-primary/20" aria-label="Add note" data-testid="button-add-note"><Plus size={16} /></button>} />{notes.length === 0 ? <EmptyInline icon={<NotebookPen />} text="Capture a thought before it wanders." action="Write a note" onClick={() => setNoteModal(true)} /> : <div className="mt-3 space-y-2">{notes.slice(0, 3).map(note => <div key={note.id} className="group flex items-start justify-between rounded-xl bg-muted/55 p-3"><button onClick={() => { setEditingNote(note); setNoteModal(true); }} className="min-w-0 text-left" data-testid={`button-edit-note-${note.id}`}><p className="truncate text-sm font-bold">{note.title}</p><p className="mt-1 line-clamp-1 text-xs text-muted-foreground">{note.body}</p></button><button onClick={() => setNotes(notes.filter(n => n.id !== note.id))} className="ml-2 rounded-lg p-1.5 text-muted-foreground opacity-60 transition hover:bg-destructive/10 hover:text-destructive md:opacity-0 md:group-hover:opacity-100" aria-label={`Delete ${note.title}`} data-testid={`button-delete-note-${note.id}`}><Trash2 size={14} /></button></div>)}</div>}</div></div>
    </div>
     <div className="mt-5 rounded-2xl border border-primary/20 bg-primary/5 p-5 sm:flex sm:items-center sm:justify-between"><div><p className="flex items-center gap-2 text-sm font-bold"><MessageCircle size={17} className="text-primary" />Study better together</p><p className="mt-1 text-xs text-muted-foreground">Get updates, reminders and a little extra motivation from the community.</p></div><button onClick={() => window.dispatchEvent(new Event('codex-open-community'))} className="mt-3 flex items-center gap-2 rounded-lg border border-primary/25 bg-card px-3 py-2 text-xs font-bold text-primary transition hover:bg-primary hover:text-primary-foreground sm:mt-0" data-testid="button-open-community">Join community <ArrowRight size={14} /></button></div>
     {effects !== 'None' && <EffectsLayer effect={effects} />}{noteModal && <NoteModal initial={editingNote} onClose={() => { setNoteModal(false); setEditingNote(null); }} onSave={addNote} />}{countdownModal && <CountdownModal initial={editingCountdown} onClose={() => { setCountdownModal(false); setEditingCountdown(null); }} onSave={saveCountdown} />}{settings && <SettingsModal theme={theme} setTheme={setTheme} effects={effects} setEffects={setEffects} onClose={() => setSettings(false)} />}
  </section>;
}

function Stat({ icon, value, label, accent }: { icon: ReactNode; value: string; label: string; accent: string }) { const tone = accent === 'secondary' ? 'bg-secondary text-secondary-foreground' : accent === 'accent' ? 'bg-accent/20 text-accent-foreground' : 'bg-primary/10 text-primary'; return <div className="rounded-2xl border border-card-border bg-card p-4"><div className={`mb-3 flex h-8 w-8 items-center justify-center rounded-lg ${tone}`}><span className="scale-[.78]">{icon}</span></div><p className="display-font text-xl font-bold">{value}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{label}</p></div>; }
function SectionTitle({ icon, title, action }: { icon: ReactNode; title: string; action?: ReactNode }) { return <div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className="text-primary">{icon}</span><h3 className="display-font text-base font-bold">{title}</h3></div>{action}</div>; }
function EmptyInline({ icon, text, action, onClick }: { icon: ReactNode; text: string; action: string; onClick: () => void }) { return <div className="mt-4 flex items-center justify-between gap-3 rounded-xl bg-muted/50 p-3.5"><div className="flex items-center gap-2 text-xs text-muted-foreground"><span className="text-primary">{icon}</span>{text}</div><button onClick={onClick} className="shrink-0 text-[11px] font-bold text-primary hover:underline" data-testid={`button-${action.toLowerCase().replace(/ /g, '-')}`}>{action}</button></div>; }
function WeeklyActivity({ activity }: { activity: string[] }) { const days = Array.from({ length: 7 }, (_, i) => { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - (6 - i)); return { key: date.toISOString().slice(0, 10), label: date.toLocaleDateString('en-IN', { weekday: 'short' }).slice(0, 1) }; }); const active = days.filter(day => activity.includes(day.key)).length; return <div className="rounded-2xl border border-card-border bg-card p-5"><SectionTitle icon={<Layers3 />} title="Weekly activity" action={<span className="text-xs font-semibold text-muted-foreground">This week</span>} /><div className="mt-5 flex h-32 items-end justify-between gap-2 sm:gap-4">{days.map(day => { const isActive = activity.includes(day.key); return <div key={day.key} className="flex flex-1 flex-col items-center gap-2"><div className="flex h-24 w-full items-end rounded-lg bg-muted/60"><div className={`w-full rounded-lg transition-all ${isActive ? 'h-full bg-primary' : 'h-2 bg-primary/20'}`} /></div><span className={`text-[10px] font-bold ${isActive ? 'text-primary' : 'text-muted-foreground'}`}>{day.label}</span></div>; })}</div><p className="mt-3 text-xs text-muted-foreground">{active ? <>You showed up <span className="font-bold text-foreground">{active} {active === 1 ? 'day' : 'days'}</span> this week.</> : 'No study sessions logged yet. Start a focus session to build your week.'}</p></div>; }

function Pomodoro({ stats, onSession }: { stats: { sessions: number; minutes: number }; onSession: () => void }) {
  const [seconds, setSeconds] = useState(25 * 60); const [running, setRunning] = useState(false);
  useEffect(() => { if (!running) return; const timer = window.setInterval(() => setSeconds(s => { if (s <= 1) { setRunning(false); onSession(); return 25 * 60; } return s - 1; }), 1000); return () => window.clearInterval(timer); }, [running, onSession]);
  const progress = `${Math.max(0, Math.min(100, (seconds / 1500) * 100))}%`; const min = String(Math.floor(seconds / 60)).padStart(2, '0'); const sec = String(seconds % 60).padStart(2, '0');
  return <div className="rounded-2xl border border-card-border bg-card p-5"><SectionTitle icon={<Timer />} title="Focus timer" action={<span className="text-xs font-semibold text-muted-foreground">{stats.sessions} sessions logged</span>} /><div className="mt-5 flex items-center gap-5"><div className="timer-ring flex h-28 w-28 shrink-0 items-center justify-center rounded-full" style={{ '--progress': progress } as React.CSSProperties}><div className="flex h-[92px] w-[92px] items-center justify-center rounded-full bg-card"><span className="display-font text-2xl font-bold">{min}:{sec}</span></div></div><div><p className="text-sm font-bold">{running ? 'Stay with it.' : 'Ready when you are.'}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">25 minutes of focus. Then take a real break.</p><div className="mt-3 flex gap-2"><button onClick={() => setRunning(!running)} className="flex items-center gap-1.5 rounded-lg bg-primary px-3 py-2 text-xs font-bold text-primary-foreground transition hover:brightness-95" data-testid="button-timer-toggle">{running ? 'Pause' : <><Play size={13} fill="currentColor" /> Start</>}</button><button onClick={() => { setRunning(false); setSeconds(1500); }} className="rounded-lg border border-border px-2.5 text-muted-foreground transition hover:text-foreground" aria-label="Reset timer" data-testid="button-timer-reset"><RotateCcw size={14} /></button></div></div></div></div>;
}

const cards = { Physics: [{ q: 'What is the SI unit of force?', a: 'Newton (N)' }, { q: 'What does Newton’s first law describe?', a: 'The law of inertia.' }], Chemistry: [{ q: 'What is Avogadro’s number?', a: '6.022 × 10²³ particles per mole.' }, { q: 'What is the pH of pure water?', a: '7 at 25°C.' }], Biology: [{ q: 'What is the powerhouse of the cell?', a: 'The mitochondria.' }, { q: 'What carries genetic information?', a: 'DNA.' }] };
function Flashcards() {
  const [subject, setSubject] = useState<keyof typeof cards>('Physics'); const [index, setIndex] = useState(0); const [flipped, setFlipped] = useState(false); const card = cards[subject][index];
  const move = (delta: number) => { setIndex(i => (i + delta + cards[subject].length) % cards[subject].length); setFlipped(false); };
  return <div className="rounded-2xl border border-card-border bg-card p-5"><SectionTitle icon={<Library />} title="Flashcards" action={<button onClick={() => { const subjects = Object.keys(cards) as (keyof typeof cards)[]; setSubject(subjects[Math.floor(Math.random() * subjects.length)]); setIndex(0); setFlipped(false); }} className="flex items-center gap-1 text-xs font-bold text-primary" data-testid="button-random-card"><Sparkles size={14} /> Random</button>} /><div className="mt-3 flex gap-1 rounded-lg bg-muted p-1">{(Object.keys(cards) as (keyof typeof cards)[]).map(s => <button key={s} onClick={() => { setSubject(s); setIndex(0); setFlipped(false); }} className={`flex-1 rounded-md py-1.5 text-[10px] font-bold transition ${subject === s ? 'bg-card text-primary shadow-sm' : 'text-muted-foreground'}`} data-testid={`button-subject-${s.toLowerCase()}`}>{s}</button>)}</div><button onClick={() => setFlipped(!flipped)} className="mt-3 min-h-[116px] w-full rounded-xl border border-primary/15 bg-primary/5 p-4 text-left transition hover:bg-primary/10" data-testid="button-flip-card"><p className="mb-2 text-[10px] font-bold uppercase tracking-widest text-primary">{flipped ? 'Answer' : 'Question'}</p><p className="display-font text-sm font-bold leading-6">{flipped ? card.a : card.q}</p><p className="mt-2 text-[10px] text-muted-foreground">{flipped ? 'Tap to see question' : 'Tap to reveal answer'}</p></button><div className="mt-3 flex items-center justify-between"><button onClick={() => move(-1)} className="rounded-lg border border-border p-2 text-muted-foreground hover:text-foreground" aria-label="Previous card" data-testid="button-previous-card"><ChevronLeft size={15} /></button><span className="text-[11px] font-bold text-muted-foreground">{index + 1} / {cards[subject].length}</span><button onClick={() => move(1)} className="rounded-lg border border-border p-2 text-muted-foreground hover:text-foreground" aria-label="Next card" data-testid="button-next-card"><ChevronRight size={15} /></button></div></div>;
}

function Modal({ title, children, onClose, wide = false }: { title: string; children: ReactNode; onClose: () => void; wide?: boolean }) { return <div className="fixed inset-0 z-50 flex items-end justify-center bg-foreground/45 p-0 backdrop-blur-sm sm:items-center sm:p-4"><div className={`page-in max-h-[90dvh] w-full overflow-y-auto rounded-t-[1.5rem] border border-card-border bg-card p-5 shadow-2xl sm:rounded-[1.5rem] ${wide ? 'max-w-lg' : 'max-w-md'}`} role="dialog" aria-modal="true"><div className="mb-5 flex items-center justify-between"><h2 className="display-font text-xl font-bold">{title}</h2><button onClick={onClose} className="rounded-full p-2 text-muted-foreground hover:bg-muted hover:text-foreground" aria-label="Close dialog" data-testid="button-close-dialog"><X size={18} /></button></div>{children}</div></div>; }
function CommunityModal({ onClose }: { onClose: () => void }) { return <Modal title="Join Our Community" onClose={onClose}><div className="mb-5 rounded-2xl bg-sidebar p-5 text-sidebar-foreground"><div className="mb-3 flex h-10 w-10 items-center justify-center rounded-xl bg-primary"><MessageCircle size={20} /></div><p className="display-font text-lg font-bold">Stay in the loop.</p><p className="mt-1 text-xs leading-5 text-sidebar-foreground/65">Stay updated with latest materials, notes, PDFs and important notifications.</p></div><div className="space-y-3"><a href="https://t.me/codexstudys" target="_blank" rel="noreferrer" onClick={onClose} className="flex items-center justify-between rounded-xl border border-border p-3 transition hover:border-primary hover:bg-primary/5" data-testid="link-community-telegram"><span className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#229ed9]/15 text-[#229ed9]"><Send size={17} /></span><span><b className="block text-sm">Join Telegram</b><small className="text-xs text-muted-foreground">@codexstudys</small></span></span><ExternalLink size={15} className="text-muted-foreground" /></a><a href="https://whatsapp.com/channel/0029VbDI2CGEAKWNSoya5L2w" target="_blank" rel="noreferrer" onClick={onClose} className="flex items-center justify-between rounded-xl border border-border p-3 transition hover:border-primary hover:bg-primary/5" data-testid="link-community-whatsapp"><span className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#25d366]/15 text-[#1aaf54]"><MessageCircle size={17} /></span><span><b className="block text-sm">Join WhatsApp Channel</b><small className="text-xs text-muted-foreground">Announcements & updates</small></span></span><ExternalLink size={15} className="text-muted-foreground" /></a></div><button onClick={onClose} className="mt-5 w-full rounded-xl border border-border py-2.5 text-xs font-bold text-muted-foreground hover:bg-muted" data-testid="button-dismiss-community">Continue to website</button></Modal>; }
function NoteModal({ initial, onClose, onSave }: { initial: Note | null; onClose: () => void; onSave: (note: Note) => void }) { const [title, setTitle] = useState(initial?.title || ''); const [body, setBody] = useState(initial?.body || ''); return <Modal title={initial ? 'Edit note' : 'New quick note'} onClose={onClose}><div className="space-y-3"><input autoFocus value={title} onChange={e => setTitle(e.target.value)} placeholder="Note title" className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none focus:border-primary" data-testid="input-note-title" /><textarea value={body} onChange={e => setBody(e.target.value)} placeholder="What do you want to remember?" rows={5} className="w-full resize-none rounded-xl border border-border bg-background p-3 text-sm outline-none focus:border-primary" data-testid="input-note-body" /><button disabled={!title.trim() || !body.trim()} onClick={() => onSave({ id: initial?.id || crypto.randomUUID(), title: title.trim(), body: body.trim(), createdAt: initial?.createdAt || new Date().toISOString() })} className="flex w-full items-center justify-center gap-2 rounded-xl bg-primary py-3 text-sm font-bold text-primary-foreground disabled:cursor-not-allowed disabled:opacity-45" data-testid="button-save-note"><Check size={16} /> Save note</button></div></Modal>; }
function CountdownModal({ initial, onClose, onSave }: { initial: Countdown | null; onClose: () => void; onSave: (item: Countdown) => void }) { const [title, setTitle] = useState(initial?.title || ''); const [date, setDate] = useState(initial?.date || ''); return <Modal title={initial ? 'Edit exam countdown' : 'Add an exam countdown'} onClose={onClose}><div className="space-y-3"><input autoFocus value={title} onChange={e => setTitle(e.target.value)} placeholder="Exam name (e.g. JEE Main)" className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none focus:border-primary" data-testid="input-countdown-title" /><label className="block text-xs font-bold text-muted-foreground">Exam date<input type="date" value={date} onChange={e => setDate(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none focus:border-primary" /></label><button disabled={!title.trim() || !date} onClick={() => onSave({ id: initial?.id || crypto.randomUUID(), title: title.trim(), date, color: 'primary' })} className="w-full rounded-xl bg-primary py-3 text-sm font-bold text-primary-foreground disabled:opacity-45" data-testid="button-save-countdown">{initial ? 'Save changes' : 'Save countdown'}</button></div></Modal>; }
function CountdownItem({ item, onEdit, onDelete }: { item: Countdown; onEdit: () => void; onDelete: () => void }) { const days = Math.max(0, Math.ceil((new Date(item.date).getTime() - Date.now()) / 86400000)); return <div className="group flex items-center justify-between rounded-xl bg-muted/55 p-3"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-accent text-accent-foreground"><Target size={17} /></div><div><p className="text-sm font-bold">{item.title}</p><p className="text-[10px] text-muted-foreground">{new Date(item.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}</p></div></div><div className="flex items-center gap-2"><span className="display-font text-lg font-bold text-primary">{days}<small className="ml-1 text-[9px] font-bold text-muted-foreground">days</small></span><button onClick={onEdit} className="rounded-lg p-1.5 text-muted-foreground opacity-60 hover:bg-primary/10 hover:text-primary md:opacity-0 md:group-hover:opacity-100" aria-label={`Edit ${item.title}`} data-testid={`button-edit-countdown-${item.id}`}><Settings size={14} /></button><button onClick={onDelete} className="rounded-lg p-1.5 text-muted-foreground opacity-60 hover:bg-destructive/10 hover:text-destructive md:opacity-0 md:group-hover:opacity-100" aria-label={`Delete ${item.title}`} data-testid={`button-delete-countdown-${item.id}`}><Trash2 size={14} /></button></div></div>; }
function EffectsLayer({ effect }: { effect: string }) { return <div className={`effect-layer effect-${effect.toLowerCase()}`} aria-hidden="true">{Array.from({ length: 14 }, (_, i) => <span key={i} style={{ '--i': i } as React.CSSProperties} />)}</div>; }
function SettingsModal({ theme, setTheme, effects, setEffects, onClose }: { theme: Theme; setTheme: (t: Theme) => void; effects: string; setEffects: (e: string) => void; onClose: () => void }) { const effectOptions = ['None', 'Fireworks', 'Rain', 'Snow', 'Lightning', 'Hail', 'Fireball', 'Storm']; return <Modal title="Profile settings" onClose={onClose} wide><div className="space-y-6"><div><div className="mb-3 flex items-center gap-2"><Palette size={16} className="text-primary" /><p className="text-sm font-bold">Choose your atmosphere</p></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{themes.map(t => <button key={t.id} onClick={() => setTheme(t.id)} className={`flex items-center gap-2 rounded-xl border px-3 py-2.5 text-left text-xs font-semibold transition ${theme === t.id ? 'border-primary bg-primary/10 text-primary' : 'border-border hover:border-primary/40'}`} data-testid={`button-theme-${t.id}`}><span className="h-3 w-3 shrink-0 rounded-full" style={{ background: t.swatch }} />{t.label}{theme === t.id && <Check size={13} className="ml-auto" />}</button>)}</div></div><div><div className="mb-3 flex items-center gap-2"><Sparkles size={16} className="text-primary" /><p className="text-sm font-bold">Animation effects</p></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{effectOptions.map(e => <button key={e} onClick={() => setEffects(e)} className={`rounded-xl border px-3 py-2 text-xs font-bold transition ${effects === e ? 'border-primary bg-primary/10 text-primary' : 'border-border text-muted-foreground hover:border-primary/40'}`} data-testid={`button-effects-${e.toLowerCase()}`}>{e}</button>)}</div><p className="mt-2 text-[11px] text-muted-foreground">Effects are off by default and saved on this device.</p></div><button onClick={onClose} className="flex w-full items-center justify-center rounded-xl bg-primary py-3 text-sm font-bold text-primary-foreground" data-testid="button-close-settings">Done</button></div></Modal>; }
function StateCard({ icon, title, body, action, onAction }: { icon: ReactNode; title: string; body: string; action: string; onAction: () => void }) { return <div className="rounded-2xl border border-dashed border-border bg-card p-10 text-center"><div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10 text-primary">{icon}</div><h3 className="display-font text-lg font-bold">{title}</h3><p className="mx-auto mt-2 max-w-sm text-sm text-muted-foreground">{body}</p><button onClick={onAction} className="mt-5 rounded-xl bg-primary px-4 py-2.5 text-xs font-bold text-primary-foreground" data-testid="button-state-action">{action}</button></div>; }
function BatchSkeleton() { return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }).map((_, i) => <div key={i} className="overflow-hidden rounded-2xl border border-card-border bg-card"><div className="skeleton aspect-[1.75/1]" /><div className="space-y-3 p-4"><div className="skeleton h-5 w-4/5 rounded" /><div className="skeleton h-3 w-3/5 rounded" /><div className="flex gap-2"><div className="skeleton h-6 w-14 rounded" /><div className="skeleton h-6 w-20 rounded" /></div><div className="skeleton mt-3 h-9 rounded-lg" /></div></div>)}</div>; }
function detectExam(b: Batch) { const text = `${b.name || ''} ${b.byName || ''} ${b.description || ''} ${b.exam || ''} ${b.category || ''}`.toUpperCase(); if (text.includes('JEE')) return 'JEE'; if (text.includes('NEET')) return 'NEET'; if (text.includes('UPSC')) return 'UPSC'; if (text.includes('CAIIB') || text.includes('CA ')) return 'CA'; if (text.includes('SSC')) return 'SSC'; if (text.includes('CBSE') || text.includes('CLASS')) return 'School'; return b.exam || b.category || 'Other'; }
function getId(b: Batch) { return String(b._id || b.id || b.slug || b.name || 'batch'); }
function getCurrentStreak(activity: string[]) { const days = new Set(activity); let streak = 0; const cursor = new Date(); cursor.setHours(0, 0, 0, 0); while (days.has(cursor.toISOString().slice(0, 10))) { streak += 1; cursor.setDate(cursor.getDate() - 1); } return streak; }
function NotFound() { return <div className="flex min-h-[70vh] flex-col items-center justify-center px-6 text-center"><div className="mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-primary/10 text-primary"><FolderOpen /></div><h1 className="display-font text-2xl font-bold">This page isn't in the syllabus.</h1><p className="mt-2 text-sm text-muted-foreground">Head back to your study space.</p><Link href="/" className="mt-5 rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground" data-testid="link-back-home">Back home</Link></div>; }

export default App;